name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate CI YAML file
        run: yamllint .github/workflows/ci.yml
      - name: 'Setup Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
          cache: npm
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}" # yamllint disable-line
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run Check
        run: npm run check
      - name: Run lint
        run: npm run lint
      - name: Run Unit-Test
        run: npm run test:unit
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E-Test
        run: npm run test
      - name: Run Coverage
        run: npm run coverage
      - name: Run Build
        run: npm run build
